using System.Security.Cryptography;
using beginner;
using beginner.scores;

//new Media().Main();
//new GPA().CalculoGPA();
//Draft.Start();
//new Dice().Start();
//Renewal.Start();
//new FraudAnalysis().Start();
//new StudentScores().Start();
//DoWhile.Start();
//RPG.Start();
//DoWhileComparison.Start2();
//VariablesDemo.Start();
//Console.WriteLine(AdicionaZeros.adicionaZeros("123", 10));
//Conversion.Start();
//ArrayManipulation.Orders();
//Formatting.Exercise();
StringManipulation.Exercise();